Repository bcgov/common-hosted-form-service, pull requests merged in 2020-12, with the labels that each got.

#109 Draft mode
  app/frontend/src/components/designer/FormDesigner.vue
  app/frontend/src/components/designer/FormViewer.vue
  app/frontend/src/components/forms/manage/AddTeamMember.vue
  app/frontend/src/components/forms/manage/CurrentDraft.vue
  app/frontend/src/components/forms/manage/ManageForm.vue
  app/frontend/src/components/forms/manage/ManageFormActions.vue
  app/frontend/src/components/forms/manage/ManageVersions.vue
  app/frontend/src/components/forms/manage/ShareForm.vue
  app/frontend/src/components/forms/manage/TeamManagement.vue
  app/frontend/src/router/index.js
  app/frontend/src/services/formService.js
  app/frontend/src/store/modules/form.js
  app/frontend/src/views/form/Design.vue
  app/frontend/src/views/form/Manage.vue
  app/frontend/src/views/form/Preview.vue
  app/frontend/src/views/form/Teams.vue
  app/frontend/tests/unit/services/formService.spec.js
  app/frontend/tests/unit/services/rbacService.spec.js
  app/frontend/tests/unit/services/roleService.spec.js
  app/frontend/tests/unit/services/userService.spec.js
  app/src/forms/form/service.js
Labels: enhancement

#112 Fix Red Alert flash before forced redirect
  app/frontend/lcov-fix.js
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/components/designer/FormViewer.vue
  app/nodemon.json
  app/package-lock.json
  app/package.json
Labels: bug, dependencies

#115 Frontend Dependency Rollback
  app/frontend/lcov-fix.js
  app/frontend/package-lock.json
  app/frontend/package.json
  app/nodemon.json
  app/package-lock.json
  app/package.json
  components/package-lock.json
  components/package.json
Labels: bug, dependencies

#116 Update Frontend Dependencies, add Keycloak Pubkey and Vetur Defaults
  app/config/custom-environment-variables.json
  app/frontend/jsconfig.json
  app/frontend/lcov-fix.js
  app/frontend/package-lock.json
  app/frontend/package.json
  app/src/components/keycloak.js
  components/package-lock.json
  openshift/README.md
  openshift/app.dc.yaml
  vetur.config.js
Labels: dependencies, enhancement

#119 Alert wasn't showing for initial draft save
  app/frontend/src/components/designer/FormDesigner.vue
Labels: bug

#124 Prepare for OCP4 Migration
  Jenkinsfile
  Jenkinsfile.cicd
  README.md
  app/package-lock.json
  openshift/commonPipeline.groovy
Labels: dependencies, enhancement
