Repository bcgov/common-hosted-form-service, pull requests merged in 2020-11, with the labels that each got.

#90 Email service for Submission notifications
  app/src/forms/email/assets/confirmation-number-email.html
  app/src/forms/email/emailService.js
  app/src/forms/form/controller.js
  app/src/forms/submission/controller.js
  app/src/forms/submission/routes.js
  app/tests/unit/routes/v1/form.spec.js
  app/tests/unit/routes/v1/submission.spec.js
Labels: enhancement

#91 Add new field (search) to user api
  app/src/forms/common/models/models.js
  app/src/forms/user/service.js
Labels: enhancement

#92 Update default values and endpoints to OIDC
  app/config/default.json
  openshift/README.md
Labels: bug

#93 Security Updates and Team Management flow updates
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/components/forms/TeamManagement.vue
  app/frontend/src/router/index.js
  app/frontend/src/services/rbacService.js
  app/package-lock.json
  app/package.json
  openshift/app.bc.yaml
Labels: bug, enhancement

#95 File Uploads / Submission Attachments
  app/app.js
  app/config/custom-environment-variables.json
  app/config/default.json
  app/config/test.json
  app/frontend/src/assets/scss/style.scss
  app/frontend/src/components/designer/FormDesigner.vue
  app/frontend/src/components/designer/FormViewer.vue
  app/frontend/src/lib/components/SimpleFile/Component.d.ts
  app/frontend/src/lib/components/SimpleFile/Component.form.d.ts
  app/frontend/src/lib/components/SimpleFile/Component.form.js
  app/frontend/src/lib/components/SimpleFile/Component.js
  app/frontend/src/lib/components/SimpleFile/editForm/Component.edit.data.d.ts
  app/frontend/src/lib/components/SimpleFile/editForm/Component.edit.data.js
  app/frontend/src/lib/components/SimpleFile/editForm/Component.edit.display.d.ts
  app/frontend/src/lib/components/SimpleFile/editForm/Component.edit.display.js
  app/frontend/src/lib/components/SimpleFile/editForm/Component.edit.file.d.ts
  app/frontend/src/lib/components/SimpleFile/editForm/Component.edit.file.js
  app/frontend/src/lib/components/index.d.ts
  app/frontend/src/lib/components/index.js
  app/frontend/src/lib/index.d.ts
  app/frontend/src/lib/index.js
  app/frontend/src/lib/providers/index.d.ts
  app/frontend/src/lib/providers/index.js
  app/frontend/src/lib/providers/storage/chefs.d.ts
  app/frontend/src/lib/providers/storage/chefs.js
  app/frontend/src/lib/providers/storage/index.d.ts
  app/frontend/src/lib/providers/storage/index.js
  app/package-lock.json
  app/package.json
  app/src/db/migrations/20201105120909_009-file-upload.js
  app/src/forms/common/constants.js
  app/src/forms/common/models/models.js
  app/src/forms/file/controller.js
  app/src/forms/file/index.js
  app/src/forms/file/middleware/upload.js
  app/src/forms/file/routes.js
  app/src/forms/file/service.js
  app/src/forms/file/storage/localStorageService.js
  app/src/forms/file/storage/objectStorageService.js
  app/src/forms/file/storage/storageService.js
  app/src/forms/form/controller.js
  app/src/forms/form/service.js
  app/src/forms/submission/service.js
  app/src/routes/v1.js
  app/tests/unit/routes/v1.spec.js
  app/tests/unit/routes/v1/form.spec.js
  components/src/components/SimpleFile/Component.form.ts
  components/src/components/SimpleFile/Component.ts
  components/src/components/SimpleFile/editForm/Component.edit.data.ts
  components/src/components/SimpleFile/editForm/Component.edit.display.ts
  components/src/components/SimpleFile/editForm/Component.edit.file.ts
  components/src/components/index.ts
  components/src/index.ts
  components/src/providers/index.ts
  components/src/providers/storage/chefs.ts
  components/src/providers/storage/index.ts
  openshift/README.md
  openshift/app.dc.yaml
Labels: enhancement

#97 Remove Team Member Functionality and UX Consistency Pass
  app/frontend/src/components/bcgov/BCGovHeader.vue
  app/frontend/src/components/designer/FormDesigner.vue
  app/frontend/src/components/designer/FormsTable.vue
  app/frontend/src/components/forms/AddTeamMember.vue
  app/frontend/src/components/forms/ExportSubmissions.vue
  app/frontend/src/components/forms/ShareForm.vue
  app/frontend/src/components/forms/SubmissionsTable.vue
  app/frontend/src/components/forms/TeamManagement.vue
  app/frontend/src/views/form/Manage.vue
  app/frontend/src/views/form/Submissions.vue
  app/frontend/src/views/user/Forms.vue
  app/frontend/tests/unit/views/form/Submissions.spec.js
  app/frontend/tests/unit/views/user/Forms.spec.js
Labels: enhancement

#99 Allow non-admin form creation and management
  app/frontend/src/components/base/BaseSecure.vue
  app/frontend/src/components/bcgov/BCGovNavBar.vue
  app/frontend/src/components/designer/FormsTable.vue
  app/frontend/src/components/forms/TeamManagement.vue
  app/frontend/src/services/rbacService.js
  app/frontend/src/views/form/Manage.vue
  app/frontend/tests/unit/components/base/BaseSecure.spec.js
  app/src/forms/auth/middleware/userAccess.js
  app/src/forms/form/routes.js
  app/src/forms/rbac/routes.js
  app/src/forms/role/routes.js
  app/src/forms/user/routes.js
  app/tests/unit/routes/v1/rbac.spec.js
Labels: bug, enhancement

#101 hide header/footer on print, hide title on submitter pages, disclaimer
  app/frontend/src/components/bcgov/BCGovFooter.vue
  app/frontend/src/components/bcgov/BCGovHeader.vue
  app/frontend/src/components/bcgov/BCGovNavBar.vue
  app/frontend/src/components/designer/FormDisclaimer.vue
  app/frontend/src/router/index.js
  app/frontend/src/views/About.vue
  app/frontend/src/views/form/Create.vue
  app/frontend/tests/unit/views/About.spec.js
  app/frontend/tests/unit/views/form/FormDisclaimer.spec.js
Labels: enhancement

#104 Add Github Actions, FE Unit Tests and conditional Submitter column hiding
  .github/workflows/unit-tests.yaml
  app/frontend/src/components/forms/TeamManagement.vue
  app/frontend/src/store/modules/form.js
  app/frontend/src/views/Form.vue
  app/frontend/tests/unit/store/modules/auth.getters.spec.js
  app/frontend/tests/unit/store/modules/notifications.mutations.spec.js
Labels: enhancement
