Repository bcgov/common-hosted-form-service, pull requests merged in 2020-09, with the labels that each got.

#12 Add minimally functional form editor
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/public/index.html
  app/frontend/src/components/designer/FormDesigner.vue
  app/frontend/src/router/index.js
  app/frontend/src/services/formService.js
  app/frontend/src/utils/constants.js
  app/frontend/src/views/Editor.vue
  app/frontend/src/views/designer/Root.vue
  app/src/forms/form/service.js
Labels: enhancement

#13 Implement Jenkins Pipeline & SonarQube
  Jenkinsfile
  Jenkinsfile.cicd
  README.md
  app/README.md
  app/frontend/tests/unit/components/bcgov/BCGovNavBar.spec.js
  app/frontend/tests/unit/router/index.spec.js
  app/package.json
  app/tests/unit/routes/v1.spec.js
  openshift/README.md
  openshift/app.bc.yaml
  openshift/app.dc.yaml
  openshift/commonPipeline.groovy
  openshift/patroni-ephemeral.dc.yaml
  openshift/patroni.dc.yaml
  openshift/patroni.secret.yaml
  sonar-project.properties
Labels: documentation, enhancement

#23 Enable TEST stage in pipeline
  Jenkinsfile
Labels: enhancement

#26 Add WIP Team Management - Display current DB state
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/components/designer/FormsTable.vue
  app/frontend/src/components/forms/SubmissionsTable.vue
  app/frontend/src/components/forms/TeamManagement.vue
  app/frontend/src/router/index.js
  app/frontend/src/services/index.js
  app/frontend/src/services/rbacService.js
  app/frontend/src/services/roleService.js
  app/frontend/src/services/userService.js
  app/frontend/src/utils/constants.js
  app/frontend/src/views/User.vue
  app/frontend/src/views/form/FormManage.vue
  app/frontend/src/views/form/FormTeams.vue
  app/package-lock.json
  app/package.json
Labels: enhancement

#27 Bugfix comp is null bug when using top-level Layout options
  app/frontend/src/components/designer/FormDesigner.vue
Labels: bug

#29 Use formio events to manage submit and reset requests.
  app/frontend/src/components/designer/FormViewer.vue
Labels: enhancement

#28 Team Management Component
  app/frontend/public/index.html
  app/frontend/src/components/designer/FormsTable.vue
  app/frontend/src/components/forms/TeamManagement.vue
  app/frontend/src/services/rbacService.js
  app/frontend/src/utils/constants.js
  app/frontend/src/views/form/FormTeams.vue
  app/src/forms/rbac/service.js
Labels: bug, enhancement

#35 Feature/qr code
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/components/forms/ShareForm.vue
Labels: enhancement

#34 Submission Access
  app/src/db/migrations/20200925103025_003-submission-users.js
  app/src/forms/common/models/models.js
  app/src/forms/common/models/utils.js
  app/src/forms/form/service.js
  app/src/forms/submission/controller.js
  app/src/forms/submission/index.js
  app/src/forms/submission/routes.js
  app/src/forms/submission/service.js
  app/src/routes/v1.js
  app/tests/unit/routes/v1.spec.js
Labels: enhancement

#36 Add IE11 Detection behavior
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/main.js
  app/package-lock.json
  app/package.json
Labels: enhancement
