Repository bcgov/common-hosted-form-service, pull requests merged in 2020-10, with the labels that each got.

#37 Change default serverUrl authentication endpoint to new gov oidc url
  app/config/default.json
Labels: enhancement

#38 Restructure vue-router to be query centric
  app/app.js
  app/frontend/src/components/bcgov/BCGovNavBar.vue
  app/frontend/src/components/designer/FormDesigner.vue
  app/frontend/src/components/designer/FormViewer.vue
  app/frontend/src/components/designer/FormsTable.vue
  app/frontend/src/components/forms/ShareForm.vue
  app/frontend/src/components/forms/SubmissionsTable.vue
  app/frontend/src/main.js
  app/frontend/src/router/index.js
  app/frontend/src/views/About.vue
  app/frontend/src/views/Editor.vue
  app/frontend/src/views/Form.vue
  app/frontend/src/views/Search.vue
  app/frontend/src/views/User.vue
  app/frontend/src/views/designer/Root.vue
  app/frontend/src/views/form/Design.vue
  app/frontend/src/views/form/FormSubmissionView.vue
  app/frontend/src/views/form/FormTeams.vue
  app/frontend/src/views/form/Manage.vue
  app/frontend/src/views/form/Submissions.vue
  app/frontend/src/views/form/Submit.vue
  app/frontend/src/views/form/Teams.vue
  app/frontend/src/views/form/ViewSubmission.vue
  app/frontend/src/views/user/Forms.vue
  app/frontend/src/views/user/History.vue
  app/frontend/src/views/user/Root.vue
  app/frontend/tests/unit/components/bcgov/BCGovNavBar.spec.js
  app/frontend/tests/unit/router/index.spec.js
  app/frontend/tests/unit/views/About.spec.js
  app/frontend/vue.config.js
Labels: bug, enhancement

#41 Fix for view not returning forms with same name
  app/src/db/migrations/20201007113516_004-alter-form-view.js
Labels: bug

#42 Add export API for forms.
  app/package-lock.json
  app/package.json
  app/src/db/migrations/20201007112921_005-submissions-data-vw.js
  app/src/forms/common/models/models.js
  app/src/forms/form/controller.js
  app/src/forms/form/exportService.js
  app/src/forms/form/routes.js
Labels: enhancement

#49 Submission Read - update FE api call.
  app/frontend/package-lock.json
  app/frontend/src/components/designer/FormViewer.vue
  app/frontend/src/services/formService.js
  app/frontend/src/store/modules/form.js
  app/src/forms/form/routes.js
Labels: bug

#51 Protect routes by CHEFS Admin role
  app/src/forms/form/routes.js
  app/src/forms/rbac/routes.js
Labels: enhancement

#52 Point all custom components to the CHEFS wiki.
  app/frontend/src/lib/components/Common/Constants.d.ts
  app/frontend/src/lib/components/Common/Constants.js
  app/frontend/src/lib/components/OrgBook/Orgbook.js
  app/frontend/src/lib/components/SimpleButtonReset/Component.js
  app/frontend/src/lib/components/SimpleButtonSubmit/Component.js
  app/frontend/src/lib/components/SimpleCheckbox/Component.js
  app/frontend/src/lib/components/SimpleCheckboxes/Component.js
  app/frontend/src/lib/components/SimpleColumns2/Component.js
  app/frontend/src/lib/components/SimpleColumns3/Component.js
  app/frontend/src/lib/components/SimpleColumns4/Component.js
  app/frontend/src/lib/components/SimpleContent/Component.js
  app/frontend/src/lib/components/SimpleDateTime/Component.js
  app/frontend/src/lib/components/SimpleDay/Component.js
  app/frontend/src/lib/components/SimpleEmail/Component.js
  app/frontend/src/lib/components/SimpleFieldSet/Component.js
  app/frontend/src/lib/components/SimpleHeading/Component.js
  app/frontend/src/lib/components/SimpleNumber/Component.js
  app/frontend/src/lib/components/SimplePanel/Component.js
  app/frontend/src/lib/components/SimpleParagraph/Component.js
  app/frontend/src/lib/components/SimplePhoneNumber/Component.js
  app/frontend/src/lib/components/SimpleRadios/Component.js
  app/frontend/src/lib/components/SimpleSelect/Component.js
  app/frontend/src/lib/components/SimpleTabs/Component.js
  app/frontend/src/lib/components/SimpleTextArea/Component.js
  app/frontend/src/lib/components/SimpleTextField/Component.js
  app/frontend/src/lib/components/SimpleTime/Component.js
  components/src/components/Common/Constants.ts
  components/src/components/OrgBook/Orgbook.ts
  components/src/components/SimpleButtonReset/Component.ts
  components/src/components/SimpleButtonSubmit/Component.ts
  components/src/components/SimpleCheckbox/Component.ts
  components/src/components/SimpleCheckboxes/Component.ts
  components/src/components/SimpleColumns2/Component.ts
  components/src/components/SimpleColumns3/Component.ts
  components/src/components/SimpleColumns4/Component.ts
  components/src/components/SimpleContent/Component.ts
  components/src/components/SimpleDateTime/Component.ts
  components/src/components/SimpleDay/Component.ts
  components/src/components/SimpleEmail/Component.ts
  components/src/components/SimpleFieldSet/Component.ts
  components/src/components/SimpleHeading/Component.ts
  components/src/components/SimpleNumber/Component.ts
  components/src/components/SimplePanel/Component.ts
  components/src/components/SimpleParagraph/Component.ts
  components/src/components/SimplePhoneNumber/Component.ts
  components/src/components/SimpleRadios/Component.ts
  components/src/components/SimpleSelect/Component.ts
  components/src/components/SimpleTabs/Component.ts
  components/src/components/SimpleTextArea/Component.ts
  components/src/components/SimpleTextField/Component.ts
  components/src/components/SimpleTime/Component.ts
  sonar-project.properties
Labels: enhancement

#48 Style form builder and rendered forms to match bc gov look/feel
  app/frontend/README.md
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/public/index.html
  app/frontend/src/assets/scss/style.scss
  app/frontend/src/components/designer/FormCreator.vue
  app/frontend/src/components/designer/FormDesigner.vue
  app/frontend/src/components/designer/FormViewer.vue
Labels: enhancement

#53 Frontend Create/Edit Form Refactor
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/assets/scss/style.scss
  app/frontend/src/components/base/BaseInfoCard.vue
  app/frontend/src/components/designer/FormCreator.vue
  app/frontend/src/components/designer/FormDesigner.vue
  app/frontend/src/components/designer/FormSettings.vue
  app/frontend/src/components/designer/FormViewer.vue
  app/frontend/src/router/index.js
  app/frontend/src/services/formService.js
  app/frontend/src/store/modules/form.js
  app/frontend/src/utils/constants.js
  app/frontend/src/utils/transformUtils.js
  app/frontend/src/views/form/Create.vue
  app/frontend/src/views/form/Design.vue
  app/frontend/src/views/form/Preview.vue
  app/frontend/src/views/form/Settings.vue
  app/frontend/src/views/form/View.vue
Labels: enhancement

#57 Load bootstrap-scss globally to fix style inconsistencies
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/assets/scss/style.scss
  app/frontend/src/components/designer/FormDesigner.vue
  app/frontend/src/components/designer/FormViewer.vue
Labels: bug

#58 Update submission success view
  app/frontend/src/components/designer/FormViewer.vue
  app/frontend/src/components/forms/SubmissionsTable.vue
  app/frontend/src/router/index.js
  app/frontend/src/views/form/Preview.vue
  app/frontend/src/views/form/Success.vue
  app/frontend/src/views/form/View.vue
Labels: enhancement

#61 Include public data in submission data (export) view
  app/src/db/migrations/20201019100738_007-public-submission-data-vw.js
Labels: bug

#62 Drop version query parameter from launch button on My Forms page
  app/frontend/src/components/designer/FormsTable.vue
Labels: bug

#67 Bugfixes: Round 1
  app/frontend/src/assets/scss/style.scss
  app/frontend/src/main.js
  app/src/forms/common/models/models.js
Labels: bug

#65 Make sure form.name is a string
  app/src/forms/common/models/models.js
Labels: bug

#68 Export Submissions - ordering, UX changes
  app/frontend/package-lock.json
  app/frontend/src/assets/scss/style.scss
  app/frontend/src/components/bcgov/BCGovHeader.vue
  app/frontend/src/components/designer/FormDesigner.vue
  app/frontend/src/components/forms/ExportSubmissions.vue
  app/frontend/src/components/forms/SubmissionsTable.vue
  app/src/forms/form/exportService.js
Labels: bug

#70 Implement BaseSecure on temporary admin restricted pages
  Jenkinsfile
  app/frontend/jest.config.js
  app/frontend/src/components/base/BaseSecure.vue
  app/frontend/src/components/designer/FormSettings.vue
  app/frontend/src/router/index.js
  app/frontend/src/store/modules/auth.js
  app/frontend/src/views/NotFound.vue
  app/frontend/src/views/Search.vue
  app/frontend/src/views/form/Create.vue
  app/frontend/src/views/form/Design.vue
  app/frontend/src/views/form/Preview.vue
  app/frontend/src/views/form/Settings.vue
  app/frontend/src/views/form/Teams.vue
  app/frontend/src/views/user/History.vue
  app/frontend/src/views/user/Root.vue
  app/frontend/tests/unit/App.spec.js
  app/frontend/tests/unit/components/base/BaseSecure.spec.js
  app/frontend/tests/unit/components/bcgov/BCGovNavBar.spec.js
  app/frontend/tests/unit/router/index.spec.js
  app/frontend/tests/unit/store/modules/auth.getters.spec.js
Labels: bug, enhancement

#69 style fixes
  app/frontend/src/assets/scss/style.scss
  app/frontend/src/components/designer/FormViewer.vue
  app/frontend/src/components/forms/ExportSubmissions.vue
  app/frontend/src/components/forms/TeamManagement.vue
Labels: bug, enhancement

#74 Add unit tests and some warning fixes
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/components/designer/FormsTable.vue
  app/frontend/src/filters/index.js
  app/frontend/src/utils/constants.js
  app/frontend/src/utils/permissionUtils.js
  app/frontend/src/utils/transformUtils.js
  app/frontend/src/views/form/Manage.vue
  app/frontend/tests/unit/filters/index.spec.js
  app/frontend/tests/unit/utils/constants.spec.js
  app/frontend/tests/unit/utils/permissionUtils.spec.js
  app/frontend/tests/unit/utils/transformUtils.spec.js
  app/package-lock.json
  app/package.json
Labels: bug, enhancement

#77 Create Load Test Utility
  load-test/README.md
  load-test/config/custom-environment-variables.json
  load-test/config/default.json
  load-test/config/production.json
  load-test/config/test.json
  load-test/index.js
  load-test/package-lock.json
  load-test/package.json
  load-test/schemas/kitchen_sink_advanced_schema.json
  load-test/schemas/kitchen_sink_no_sig_schema.json
  load-test/submissions/kitchen_sink_advanced_submission.json
  load-test/submissions/kitchen_sink_no_sig_submission.json
  sonar-project.properties
Labels: enhancement

#78 Route/Controller Basic Unit Tests
  app/tests/unit/routes/v1/admin.spec.js
  app/tests/unit/routes/v1/form.spec.js
  app/tests/unit/routes/v1/permission.spec.js
  app/tests/unit/routes/v1/rbac.spec.js
  app/tests/unit/routes/v1/role.spec.js
  app/tests/unit/routes/v1/submission.spec.js
Labels: enhancement

#80 Frontend Unit Test Additions
  README.md
  app/frontend/src/views/user/Root.vue
  app/frontend/tests/unit/components/base/BaseCopyToClipboard.spec.js
  app/frontend/tests/unit/components/base/BaseImagePopout.spec.js
  app/frontend/tests/unit/components/base/BaseNotificationBar.spec.js
  app/frontend/tests/unit/components/base/BaseNotificationContainer.spec.js
  app/frontend/tests/unit/views/Form.spec.js
  app/frontend/tests/unit/views/NotFound.spec.js
  app/frontend/tests/unit/views/User.spec.js
  app/frontend/tests/unit/views/form/Design.spec.js
  app/frontend/tests/unit/views/form/Preview.spec.js
  app/frontend/tests/unit/views/form/Submissions.spec.js
  app/frontend/tests/unit/views/form/Submit.spec.js
  app/frontend/tests/unit/views/form/Success.spec.js
  app/frontend/tests/unit/views/form/Teams.spec.js
  app/frontend/tests/unit/views/form/View.spec.js
  app/frontend/tests/unit/views/user/Forms.spec.js
  app/frontend/tests/unit/views/user/History.spec.js
  app/frontend/tests/unit/views/user/Root.spec.js
  app/jest.config.js
  components/README.md
  load-test/README.md
  openshift/patroni.dc.yaml
Labels: enhancement

#82 Feature/team mgmt api enhancements
  app/frontend/src/components/forms/TeamManagement.vue
  app/src/forms/common/models/models.js
  app/src/forms/user/controller.js
  app/src/forms/user/index.js
  app/src/forms/user/routes.js
  app/src/forms/user/service.js
  app/src/routes/v1.js
  app/tests/unit/routes/v1.spec.js
  app/tests/unit/routes/v1/user.spec.js
Labels: enhancement

#83 API for form delete (soft).
  app/src/forms/auth/middleware/userAccess.js
  app/src/forms/auth/service.js
  app/src/forms/common/models/models.js
  app/src/forms/common/utils.js
  app/src/forms/form/controller.js
  app/src/forms/form/routes.js
  app/src/forms/form/service.js
  app/src/forms/rbac/controller.js
  app/src/forms/rbac/service.js
  app/tests/unit/forms/common/utils.spec.js
Labels: enhancement

#86 Delete button
  app/frontend/src/components/base/BaseDialog.vue
  app/frontend/src/components/designer/FormsTable.vue
  app/frontend/src/services/formService.js
  app/frontend/src/store/modules/form.js
  app/frontend/src/views/form/Manage.vue
Labels: enhancement
