Repository bcgov/common-hosted-form-service, pull requests merged in 2021-11, with the labels that each got.

#259 General Cypress Functional Test Maintenance
  tests/functional/cypress/fixtures/kitchensink/formOptions.json
  tests/functional/cypress/fixtures/kitchensink/formVersion.json
  tests/functional/cypress/fixtures/kitchensink/meta.json
  tests/functional/cypress/fixtures/kitchensink/submissionOptions.json
  tests/functional/cypress/package-lock.json
  tests/functional/cypress/package.json
  tests/functional/cypress/specs/kitchen-sink.spec.js
Labels: bug, dependencies

#257 Return to User
  app/frontend/src/components/forms/FormSubmission.vue
  app/frontend/src/components/forms/SubmissionsTable.vue
  app/frontend/src/components/forms/submission/StatusPanel.vue
  app/frontend/src/store/modules/form.js
  app/frontend/tests/unit/store/modules/form.actions.spec.js
  app/src/db/migrations/20211027000000_024-add-revising.js
  app/src/docs/v1.api-spec.yaml
  app/src/forms/common/constants.js
  app/src/forms/email/assets/bodies/send-status-revising-email-body.html
  app/src/forms/email/emailService.js
  app/src/forms/form/service.js
  app/src/forms/permission/service.js
  app/src/forms/submission/controller.js
  app/src/forms/submission/service.js
  app/tests/unit/forms/email/emailService.spec.js
  app/tests/unit/forms/submission/controller.spec.js
  app/tests/unit/forms/submission/service.spec.js
  app/tests/unit/routes/v1/submission.spec.js
Labels: bug, enhancement

#256 Update to Node 16 LTS
  .github/workflows/unit-tests.yaml
  app/.eslintrc.js
  app/app.js
  app/frontend/.eslintrc.js
  app/frontend/component-update.js
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/utils/constants.js
  app/frontend/tests/unit/utils/constants.spec.js
  app/package-lock.json
  app/package.json
  app/src/db/migrations/20210129120337_012-submission-status.js
  app/src/db/migrations/20211027000000_024-add-revising.js
  app/src/forms/admin/service.js
  app/src/forms/auth/service.js
  app/src/forms/common/constants.js
  app/src/forms/common/models/jsonSchema.js
  app/src/forms/common/models/tables/formSubmission.js
  app/src/forms/common/models/tables/formVersion.js
  app/src/forms/common/models/tables/formVersionDraft.js
  app/src/forms/common/models/tables/submissionAudit.js
  app/src/forms/common/models/tables/userFormPreferences.js
  app/src/forms/email/emailService.js
  app/src/forms/file/middleware/filePermissions.js
  app/src/forms/form/service.js
  app/src/forms/rbac/service.js
  app/src/forms/user/service.js
  app/tests/common/dbHelper.js
  app/tests/unit/forms/email/emailService.spec.js
  app/tests/unit/forms/file/middleware/filePermissions.spec.js
  app/tests/unit/forms/rbac/controller.spec.js
  app/tests/unit/forms/user/service.spec.js
  components/package-lock.json
  components/package.json
  components/src/providers/storage/chefs.ts
  openshift/app.bc.yaml
Labels: bug, enhancement, dependencies
