Repository bcgov/common-hosted-form-service, pull requests merged in 2021-06, with the labels that each got.

#176 Form Designer Unification
  app/frontend/.eslintrc.js
  app/frontend/src/components/designer/FormDesigner.vue
Labels: enhancement

#186 JSON Logging Refactor
  app/app.js
  app/bin/www
  app/config/custom-environment-variables.json
  app/config/default.json
  app/knexfile.js
  app/package-lock.json
  app/package.json
  app/src/components/cdogsService.js
  app/src/components/chesService.js
  app/src/components/clientConnection.js
  app/src/components/errorToProblem.js
  app/src/components/log.js
  app/src/db/dataConnection.js
  app/src/forms/email/emailService.js
  app/src/forms/file/storage/objectStorageService.js
  app/tests/common/helper.js
  app/tests/unit/components/errorToProblem.spec.js
  app/tests/unit/components/log.spec.js
  app/tests/unit/routes/v1.spec.js
  app/tests/unit/routes/v1/admin.spec.js
  app/tests/unit/routes/v1/form.spec.js
  app/tests/unit/routes/v1/permission.spec.js
  app/tests/unit/routes/v1/rbac.spec.js
  app/tests/unit/routes/v1/role.spec.js
  app/tests/unit/routes/v1/submission.spec.js
  app/tests/unit/routes/v1/user.spec.js
  openshift/README.md
Labels: dependencies, documentation, enhancement

#190 Revert "Merge pull request #187 from MichaelChung123/dev-1765"
  components/src/components/SimpleContent/Component.ts
Labels: bug

#189 General Usability Bugfixes
  app/frontend/src/components/base/BaseCopyToClipboard.vue
  app/frontend/src/components/designer/FormDesigner.vue
  app/frontend/src/components/designer/FormViewer.vue
  app/frontend/src/components/designer/FormsTable.vue
  app/frontend/src/components/forms/ExportSubmissions.vue
  app/frontend/src/components/forms/FormSubmission.vue
  app/frontend/src/components/forms/SubmissionsTable.vue
  app/frontend/src/components/forms/manage/AddTeamMember.vue
  app/frontend/src/components/forms/manage/ManageFormActions.vue
  app/frontend/src/components/forms/manage/ShareForm.vue
  app/frontend/src/components/forms/submission/AuditHistory.vue
  app/frontend/src/components/forms/submission/MySubmissionsTable.vue
  app/frontend/src/components/forms/submission/StatusPanel.vue
  app/frontend/vue.config.js
Labels: bug

#192 Add Fluent-Bit Sidecar Support
  openshift/README.md
  openshift/app.dc.yaml
  openshift/commonPipeline.groovy
  openshift/fluent-bit.cm.yaml
Labels: documentation, enhancement

#194 Add Print Button
  app/frontend/src/App.vue
  app/frontend/src/assets/scss/style.scss
  app/frontend/src/components/base/BaseAuthButton.vue
  app/frontend/src/components/base/BasePrintButton.vue
  app/frontend/src/components/bcgov/BCGovFooter.vue
  app/frontend/src/components/bcgov/BCGovHeader.vue
  app/frontend/src/components/bcgov/BCGovNavBar.vue
  app/frontend/src/components/forms/FormSubmission.vue
  app/frontend/src/views/Admin.vue
  app/frontend/src/views/Form.vue
  app/frontend/src/views/User.vue
  app/frontend/src/views/form/Success.vue
  app/frontend/src/views/form/View.vue
  app/frontend/tests/unit/components/base/BasePrintButton.spec.js
  app/frontend/tests/unit/views/Form.spec.js
  app/frontend/tests/unit/views/form/Success.spec.js
Labels: enhancement

#195 order csv export columns
  .github/workflows/unit-tests.yaml
  app/src/forms/form/exportService.js
Labels: bug, enhancement
