Repository bcgov/common-hosted-form-service, pull requests merged in 2021-02, with the labels that each got.

#137 Unused form fetch in settings
  app/frontend/src/components/designer/FormSettings.vue
  app/frontend/src/store/modules/form.js
  app/frontend/src/views/form/Manage.vue
Labels: bug

#138 Refactor preserve/prebuild script to be written in node.js
  app/frontend/component-update.js
  app/frontend/formio.sh
  app/frontend/package.json
  app/frontend/src/main.js
Labels: bug, enhancement

#140 Add Code Climate support to GA Pipeline
  .github/workflows/unit-tests.yaml
  Jenkinsfile
  Jenkinsfile.cicd
  README.md
  app/frontend/jest.config.js
  app/frontend/lcov-fix.js
  app/frontend/package-lock.json
  app/frontend/package.json
  app/jest.config.js
  app/package-lock.json
  app/package.json
  openshift/commonPipeline.groovy
  sonar-project.properties
Labels: bug, documentation, enhancement

#141 Skip coverage steps if CC test reporter is missing
  .github/workflows/unit-tests.yaml
Labels: bug

#142 Make draft look like the next version
  app/frontend/src/components/designer/FormDesigner.vue
  app/frontend/src/components/forms/manage/ManageForm.vue
  app/frontend/src/components/forms/manage/ManageVersions.vue
  app/frontend/src/views/form/Manage.vue
Labels: bug, enhancement

#144 Realign frontend package.json dependencies
  app/frontend/package-lock.json
  app/frontend/package.json
  app/frontend/src/components/designer/FormDesigner.vue
  app/frontend/src/components/designer/FormSettings.vue
  app/frontend/src/components/designer/FormViewer.vue
  app/package-lock.json
  app/package.json
  app/src/routes/v1.js
Labels: bug

#146 Mass CodeClimate Plugin cleanup
  .codeclimate.yml
  .editorconfig
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  CODE-OF-CONDUCT.md
  CONTRIBUTING.md
  _config.yml
  app/.eslintrc.js
  app/.prettierrc
  app/frontend/.eslintrc.js
  app/frontend/.prettierrc
  app/frontend/src/assets/scss/style.scss
  app/src/db/.editorconfig
  app/src/db/migrations/20200807133615_000-init.js
  app/src/db/migrations/20200825155537_001-views.js
  app/src/db/migrations/20200925103025_003-submission-users.js
  app/src/db/migrations/20201007112921_005-submissions-data-vw.js
  app/src/db/migrations/20201008142046_006-version-drafts.js
  app/src/db/migrations/20201019100738_007-public-submission-data-vw.js
  app/src/db/migrations/20201105120909_009-file-upload.js
  app/src/docs/.editorconfig
  app/src/docs/CHEFS_API_Documentation.postman_collection.json
  app/src/forms/email/assets/confirmation-number-email.html
  app/src/forms/file/storage/objectStorageService.js
  components/src/components/OrgBook/editForm/Orgbook.edit.data.ts
  components/src/components/OrgBook/editForm/Orgbook.edit.display.ts
  components/src/components/OrgBook/editForm/Orgbook.edit.validation.ts
  components/src/components/SimpleCheckbox/editForm/Component.edit.display.ts
  components/src/components/SimpleDateTime/editForm/Component.edit.display.ts
  components/src/components/SimpleDay/editForm/Component.edit.display.ts
  components/src/components/SimpleEmail/editForm/Component.edit.display.ts
  components/src/components/SimpleFile/editForm/Component.edit.display.ts
  components/src/components/SimpleNumber/editForm/Component.edit.display.ts
  components/src/components/SimpleTime/editForm/Component.edit.display.ts
  components/src/use.ts
  load-test/config/test.json
  load-test/index.js
  load-test/schemas/kitchen_sink_advanced_schema.json
  vetur.config.js
Labels: enhancement

#147 Improve Frontend Test Coverage
  app/frontend/jest.config.js
  app/frontend/package.json
  app/frontend/src/store/index.js
  app/frontend/src/store/modules/form.js
  app/frontend/tests/unit/store/index.spec.js
  app/frontend/tests/unit/store/modules/admin.getters.spec.js
  app/frontend/tests/unit/store/modules/admin.mutations.spec.js
  app/frontend/tests/unit/store/modules/form.actions.spec.js
  app/frontend/tests/unit/store/modules/form.getters.spec.js
  app/frontend/tests/unit/store/modules/form.mutations.spec.js
  app/frontend/tests/unit/store/modules/notifications.actions.spec.js
  app/frontend/tests/unit/store/modules/notifications.mutations.spec.js
  app/frontend/tests/unit/utils/permissionUtils.spec.js
  app/frontend/tests/unit/views/Admin.spec.js
  app/frontend/tests/unit/views/form/Submit.spec.js
  app/package.json
Labels: enhancement

#149 Migrate to Kubernetes NetworkPolicies
  openshift/README.md
  openshift/app.dc.yaml
  openshift/patroni-ephemeral.dc.yaml
  openshift/patroni.dc.yaml
Labels: documentation, enhancement
