Repository bcgov/common-hosted-form-service, pull requests merged in 2024-05, with the labels that each got.

#1339 fix/FORMS-1215 csv export of datagrid data
  app/src/forms/form/exportService.js
  app/tests/fixtures/submission/kitchen_sink_submission_data_export_datagrid_fields_selection.json
  app/tests/unit/README.md
  app/tests/unit/forms/form/exportService.spec.js
Labels: bug, documentation

#1340 fix/FORMS-1208 remove crypto dependency
  app/package-lock.json
  app/package.json
  app/src/components/cdogsService.js
  app/tests/unit/components/cdogsService.spec.js
Labels: dependencies

#1332 Bug Fix: 401 Error for the Form Subscriptions
  app/frontend/src/components/forms/manage/ManageForm.vue
  app/frontend/tests/unit/components/forms/manage/ManageForm.spec.js
Labels: bug

#1347 fix: FORMS-1203 update express dependency
  app/package-lock.json
  app/package.json
Labels: dependencies

#1331 Bug Fix: Error When Choosing Not to Unpublish a Form
  app/frontend/src/components/forms/manage/ManageVersions.vue
  app/frontend/tests/unit/components/forms/manage/ManageVersions.spec.js
Labels: bug
